## Numpy 
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these array

**Ways to install Numpy**
* conda install numpy
* pip install numpy

##### Using NumPy
Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

##### Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

##### Creating NumPy Arrays

##### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
mylist= [1,2,3]
mylist

[1, 2, 3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

**arange** - Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**zeros and ones** - Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**linspace** - Return evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**eye** -Creates an identity matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)

In [22]:
np.random.rand(2)

array([0.39011444, 0.16936946])

In [23]:
np.random.rand(5,5)

array([[0.90315354, 0.15124379, 0.6191646 , 0.1180938 , 0.99649689],
       [0.45498426, 0.7288789 , 0.92604989, 0.79386508, 0.42884767],
       [0.52850267, 0.38134183, 0.04455143, 0.21209484, 0.49796611],
       [0.22322814, 0.52164037, 0.24673177, 0.47315463, 0.67686009],
       [0.81659744, 0.86973047, 0.4692423 , 0.26567812, 0.74645179]])

### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [25]:
np.random.randn(2)

array([-0.61513364,  1.06337468])

In [26]:
np.random.randn(5,5)

array([[-1.96856875,  0.81793023, -0.77984294,  1.1308542 , -0.73463934],
       [-0.92090183, -0.89855031,  1.11628154,  0.22348328,  2.03435242],
       [-1.15099378, -0.00806898, -0.8670286 ,  0.11559092,  0.07887806],
       [-1.04851115,  0.11932904,  0.9159419 , -0.60750729, -2.51197817],
       [ 0.87159469, -0.79792238,  0.24815074,  2.12309109, -0.27905556]])

### randint 
Return random integer from low (inclusive) to high (exclusive)

In [27]:
np.random.randint(1,100)

89

In [28]:
np.random.randint(1,100,10)

array([42, 36, 12, 88, 51, 89, 70, 33, 35, 35])

### Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [29]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([ 7, 28, 18, 41,  5, 25, 23, 22, 45, 37])

#### Reshape
Returns an array containing the same data with a new shape.

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [34]:
ranarr

array([ 7, 28, 18, 41,  5, 25, 23, 22, 45, 37])

In [35]:
ranarr.max()

45

In [36]:
ranarr.argmax()

8

In [37]:
ranarr.min()

5

In [38]:
ranarr.argmin()

4

#### Shape
Shape is an attribute that arrays have (not a method):

In [39]:
#Vector 
arr.shape

(25,)

In [40]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [41]:
arr.reshape(1,25).shape

(1, 25)

In [42]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [43]:
arr.reshape(25,1).shape

(25, 1)

#### dtype

You can also grab the data type of the object in the array:

In [44]:
arr.dtype

dtype('int64')