# NumPy Indexing and Selection

How to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [3]:
#Sample Array 
arr=np.arange(0,11)

In [4]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [6]:
#Get a value at an index
arr[8]

8

In [7]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [8]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [10]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

###### Now note the changes also occur in our original array!

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

###### Data is not copied, it's a view of the original array! This avoids memory problems!

In [17]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d[1]

array([20, 25, 30])

In [20]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [21]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [22]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [23]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Selection

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
bool_arr = arr>4

In [27]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])