## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [3]:
import numpy as np
arr=np.arange(0,10)

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/var/folders/rd/8jzqyjcj6k9gtbnyj_x9shx80000gn/T/ipykernel_13073/2878212635.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
# Also warning, but not an error instead infinity
1/arr

/var/folders/rd/8jzqyjcj6k9gtbnyj_x9shx80000gn/T/ipykernel_13073/1360216608.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones: